allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  duckdb: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@nuxt/ui@4.10.0'
overrides:
  linkify-it: 5.0.2
