export const DASHBOARD_GRID_COLUMNS = 12
export const DASHBOARD_GRID_ROW_HEIGHT = 96
export const DASHBOARD_GRID_GAP = 8
export const DASHBOARD_GRID_MIN_ROWS = 12
export const DASHBOARD_GRID_MIN_HEIGHT = DASHBOARD_GRID_ROW_HEIGHT * DASHBOARD_GRID_MIN_ROWS
